export const ROUTES = {
    CURRENCIES: "/admin/currencies",
    EDIT_CURRENCY: "/admin/currencies/edit",
    CURRENCY_FIELDS: "/admin/currency-fields",
    EDIT_CURRENCY_FIELD: "/admin/currency-fields/edit",
    DIRECTIONS: "/admin/directions",    
    EDIT_DIRECTION: "/admin/directions/edit",
    DIRECTION_ADD_GROUP: "/admin/directions/add-group",
    FORMULAS: "/admin/formulas",
    EDIT_FORMULA: "/admin/formulas/edit",
    COURSES: "/admin/courses",
    ORDERS: "/admin/orders",
    ORDER_LOG: "/admin/orders/log",    
    EDIT_ORDER: "/admin/orders/edit",
    ORDER_STATUS: "/admin/order-status",
    EDIT_ORDER_STATUS: "/admin/order-status/edit",
    BONUS: "/admin/bonus",
    BONUS_USERS: "/admin/bonus/for-users",
    BONUS_USER_ORDERS: "/admin/bonus/user-orders",
    BONUS_REFERRALS: "/admin/bonus/for-referrals",  
    BONUS_REFERRAL_ORDERS: "/admin/bonus/referral-orders",
    NOTIFY_ADMIN: "/admin/notify/for-admin",
    NOTIFY_USER: "/admin/notify/for-user",
    OPTIONS: "/admin/options",
    EDIT_TIMETABLE: "/admin/timetable",
    USERS: "/admin/users",
    EDIT_USER: "/admin/users/edit",
    ROLES: "/admin/roles",
    EDIT_ROLE: "/admin/roles/edit",
    REVIEWS: "/admin/reviews",
    EDIT_REVIEW: "/admin/reviews/edit",
    NEWS: "/admin/news",
    EDIT_NEWS: "/admin/news/edit",
    OPTIONS_GARANTEX: "/admin/exchanges/garantex",
    OPTIONS_BYBIT: "/admin/exchanges/bybit",
    OPTIONS_BINANCE: "/admin/exchanges/binance",
    OPTIONS_COINMARKETCAP: "/admin/exchanges/coinmarketcap",
    OPTIONS_CBR: "/admin/exchanges/cbr", 
    OPTIONS_MEXC: "/admin/exchanges/mexc",   
    LOGIN: "/login",
    LOGOUT: "/logout",        
    ADMIN: "/admin",
    STOP_WORDS: "/admin/stopwords",
        
    //website
    WEBSITE: "/",
    CHECKUP_ORDER: "/checkup-order",
    RULES: "/rules",
    CONTACTS: "/contacts",
    WEBSITE_NEWS: "/news",
    WEBSITE_REVIEWS: "/reviews",
    
    //website - authorized user
    MY_ORDERS: "/user/orders",
    ORDER_BY_ID: "/user/order",
    MY_REVIEWS: "/user/reviews",
    MY_REVIEW_BY_ID: "/user/review",    
    ACCOUNT: "/user/account",  
    REFERRALS: "/user/referrals",  
    CASHBACK: "/user/cashback",
  };
  